webapp/contrato/forms.py
from flask import flash
from flask_login import current_user
from flask_wtf import FlaskForm as Form
from wtforms import StringField, SelectField, SubmitField, BooleanField, IntegerField
from wtforms.validators import InputRequired, Length, NumberRange

from webapp.contrato.models import Contrato


class ContratoForm(Form):
    """    Classe do formulário de contrato de assinaturas    """
    id = IntegerField('id')
    nome = StringField('Nome', validators=[InputRequired(), Length(max=50)],
                       render_kw={"placeholder": "Digite o nome do contrato"})
    tela = SelectField('Telas', choices=[], validate_choice=False, coerce=int)
    ativo = BooleanField('Ativo')
    submit = SubmitField("Cadastrar")

    def validate(self, **kwargs) -> bool:
        """        Função que válida as informações do formulário        """
        check_validate = super(ContratoForm, self).validate()  # valida de forma inicial as informações

        if check_validate:  # checa a validação inicial
            # busca se existe algum contrato com o nome
            if Contrato.query.filter(Contrato.id != self.id.data,
                                     Contrato.nome == self.nome.data,
                                     Contrato.empresa_gestora_id == current_user.empresa_id
                                     ).one_or_none():
                flash(f'Já existe um contrato com este nome', category="danger")
                return False
        else:
            flash("Contrato não válidado", category="danger")
            return False

        return True


class TelaContratoForm(Form):
    """    Formulário o relacionamento Contrato de assinatura e Telas    """
    tela = SelectField('Telas', choices=[], validate_choice=False, coerce=int)
    submit = SubmitField("Cadastrar")

    def validate(self, **kwargs):
        """    Função que válida as informações do formulário    """
        check_validate = super(TelaContratoForm, self).validate()  # válida inicialmente as informações
        if check_validate:
            if self.tela.data == 0:
                flash("Tela não selecionada", category="danger")
                return False
            return True
        else:
            return False


class TelaForm(Form):
    """    Formulário das Telas    """
    nome = StringField('Nome', validators=[InputRequired(), Length(max=50)],
                       render_kw={"placeholder": "Digite o nome da tela"})
    icon = StringField('Icone', validators=[InputRequired(), Length(max=50)],
                       render_kw={"placeholder": "Digite o nome do icone"})
    url = StringField('URL', validators=[InputRequired(), Length(max=50)],
                      render_kw={"placeholder": "Digite o endereço da url"})
    posicao = IntegerField('Posição', validators=[InputRequired(), NumberRange(min=0)],
                           render_kw={"placeholder": "Digite a posição"})

    submit = SubmitField("Cadastrar")

    def validate(self, **kwargs):
        # if our validators do not pass
        # check_validate = super(EmpresaForm, self).validate()
        # if not check_validate:
        #     return False

        # flash("Empresa não adicionada", category="danger")
        return True

webapp/ordem_servico/forms.py
from flask_wtf import FlaskForm as Form
from wtforms import IntegerField, StringField, DateField, BooleanField, TextAreaField, SubmitField, SelectField, \
    FileField
from wtforms.validators import InputRequired, Length, Optional
from flask import flash
from flask_login import current_user


class OrdemServicoForm(Form):
    descricao = StringField('Descrição', validators=[InputRequired(), Length(max=50)],
                            render_kw={"placeholder": "Descrição da atividade"})
    tipo = SelectField('Tipo de Ordem', choices=[], coerce=int)
    equipamento = SelectField('Equipamento', choices=[], coerce=int)

    submit = SubmitField("Salvar")

    def validate(self, **kwargs):

        check_validate = super(OrdemServicoForm, self).validate()

        if check_validate:
            if self.equipamento.data == 0:
                flash("Equipamento não informado", category="danger")
                return False
            elif self.tipo.data == 0:
                flash("Tipo de Ordem não informado", category="danger")
                return False
            else:
                return True

        return False


class TramitacaoForm(Form):
    observacao = TextAreaField('Observação', validators=[InputRequired()],
                               render_kw={"placeholder": "Informe a observação"})
    tiposituacaoordem = SelectField('Situação', choices=[], coerce=int, validate_choice=False)
    submit = SubmitField("Salvar")

    def validate(self, **kwargs):
        check_validate = super(TramitacaoForm, self).validate()
        if check_validate:
            if self.tiposituacaoordem.data == 0:
                flash("Tipo da situação não informada", category="danger")
                return False
            else:
                return True

        return False

webapp/supplier/forms.py
from flask_wtf import FlaskForm as Form
from wtforms import StringField, IntegerField, SelectField, \
    PasswordField, BooleanField, SubmitField
from wtforms.validators import InputRequired, Length, EqualTo, Email, Regexp
from .models import Supplier
from flask import flash


class SupplierForm(Form):
    nome = StringField('Nome', validators=[InputRequired(), Length(max=50)],
                       render_kw={"placeholder": "Digite o nome do sub-ramo de negócios"})
    company = SelectField('Empresa', choices=[], coerce=int)
    submit = SubmitField("Cadastrar")

    def validate(self):
        return True

webapp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_mail import Mail

db = SQLAlchemy()
migrate = Migrate()
# debug_toolbar = DebugToolbarExtension()
mail = Mail()


def create_app(object_name: str) -> Flask:
    """Criar a aplicação com os recursos"""
    app = Flask(__name__)
    app.config.from_object(object_name)
    db.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    # debug_toolbar.init_app(app)

    from webapp.usuario import criar_modulo as criar_modulo_usuario
    from webapp.main import criar_modulo as criar_modulo_main
    from webapp.sistema import criar_modulo as criar_modulo_sistema
    from webapp.empresa import criar_modulo as criar_modulo_empresa
    from webapp.equipamento import criar_modulo as criar_modulo_equipamento
    from webapp.supplier import criar_modulo as criar_modulo_fornecedor
    from webapp.contrato import criar_modulo as criar_modulo_contrato
    from webapp.plano_manutencao import criar_modulo as criar_modulo_plano_manutencao
    from webapp.ordem_servico import criar_modulo as criar_modulo_ordem_servico

    criar_modulo_usuario(app)
    criar_modulo_main(app)
    criar_modulo_sistema(app)
    criar_modulo_empresa(app)
    criar_modulo_equipamento(app)
    criar_modulo_fornecedor(app)
    criar_modulo_contrato(app)
    criar_modulo_plano_manutencao(app)
    criar_modulo_ordem_servico(app)

    # app.register_error_handler(404, page_not_found)
    return app

webapp/contrato/__init__.py
def criar_modulo(app, **kwargs):
    """Cria o módulo do controlador - Planos de assinatura"""
    from .controllers import contrato_blueprint
    app.register_blueprint(contrato_blueprint)

webapp/empresa/__init__.py
def criar_modulo(app, **kwargs):
    """    Cria o módulo do controlador - Empresas    """
    from .controllers import empresa_blueprint
    app.register_blueprint(empresa_blueprint)

webapp/empresa/controllers.py
import numpy as np
import pandas as pd
from flask import (render_template, Blueprint,
                   redirect, url_for,
                   flash, Response)
from flask_login import current_user, login_required, login_user

import config
from webapp.contrato.models import Contrato
from webapp.contrato.models import Telacontrato
from webapp.empresa.forms import EmpresaForm, EmpresaSimplesForm, RegistroInteressadoForm
from webapp.empresa.models import Interessado, Tipoempresa, Empresa
from webapp.sistema.models import LogsEventos
from webapp.usuario import has_view
from webapp.usuario.models import Senha, Usuario, PerfilAcesso, TelaPerfilAcesso
from webapp.utils.email import send_email
from webapp.utils.erros import flash_errors
from webapp.utils.files import lista_para_csv
from webapp.utils.objetos import salvar, excluir, preencher_objeto_atributos_semvinculo, \
    preencher_objeto_atributos_datas, criptografar_id_lista
from webapp.utils.tools import create_token, verify_token, descriptografar

empresa_blueprint = Blueprint(
    'empresa',
    __name__,
    template_folder='../templates/sistema/empresa',
    url_prefix="/sistema"
)


@empresa_blueprint.route('/empresa_listar', methods=['GET', 'POST'])
@login_required
@has_view('Empresa')
def empresa_listar() -> str:
    LogsEventos.registrar("evento", empresa_listar.__name__)
    """    Retorna a lista de empresas vinculada a empresa do usuario     """
    empresas = Empresa.query.filter_by(empresa_gestora_id=current_user.empresa_id)  # retorna uma lista com base no _

    criptografar_id_lista(empresas)

    return render_template('empresa_listar.html', empresas=empresas)


@empresa_blueprint.route('/empresa_cliente', methods=['GET', 'POST'])
@login_required
@has_view('Empresa')
def empresa_cliente() -> str:
    LogsEventos.registrar("evento", empresa_cliente.__name__)
    """    Retorna a lista de empresas vinculada a empresa do usuario     """
    empresa = Empresa.localizar_empresa_by_id(1)
    empresas = {empresa.nome_fantasia: Empresa.lista_clientes(current_user.empresa_id)}

    return render_template('empresa_cliente.html', empresas=empresas)


# def lista_clientes(id_):
#     clientes = Empresa.query.filter(
#         Empresa.id != 1,
#         Empresa.empresa_gestora_id == id_).all()
#
#     return [{cliente.nome_fantasia: lista_clientes(cliente.id)} for cliente in clientes]


@empresa_blueprint.route('/empresa_ativar/<empresa_id_crypto>', methods=['GET', 'POST'])
@login_required
@has_view('Empresa')
def empresa_ativar(empresa_id_crypto):
    # Decriptografar os ids
    empresa_id = descriptografar(empresa_id_crypto)

    LogsEventos.registrar("evento", empresa_ativar.__name__, empresa_id=empresa_id)
    """    Função que ativa/desativa uma empresa    """

    empresa = Empresa.localizar_empresa_by_id(empresa_id)
    if empresa:  # se a empresa existir
        ativo = empresa.ativo

        # caso a empresa não esteja ativa
        if not ativo:
            # caso o contrato não esteja ativo
            if not empresa.contrato.ativo:
                flash("O contrato desta empresa não está ativo", category="danger")
                return redirect(url_for('empresa.empresa_listar'))

        empresa.ativar_desativar()  # ativa/inativa a empresa
        if salvar(empresa):  # salva no banco de dados a alteração
            if ativo:
                flash("Empresa desativada com sucesso", category="success")
            else:
                flash("Empresa ativada com sucesso", category="success")
        else:
            flash("Erro ao ativar/desativar empresa", category="danger")

    else:
        flash("Empresa não registrada", category="danger")
    return redirect(url_for('empresa.empresa_listar'))


@empresa_blueprint.route('/empresa_excluir/<empresa_id_crypto>', methods=['GET', 'POST'])
@login_required
@has_view('Empresa')
def empresa_excluir(empresa_id_crypto):
    # Decriptografar os ids
    empresa_id = descriptografar(empresa_id_crypto)

    LogsEventos.registrar("evento", empresa_excluir.__name__, empresa_id=empresa_id)
    """Função para excluir uma empresa"""

    # localizar uma empresa
    empresa = Empresa.localizar_empresa_by_id(empresa_id)
    if empresa:
        if excluir(empresa):
            flash("Empresa excluída", category="success")
        else:
            flash("Erro ao excluir a empresa", category="danger")
    else:
        flash("Empresa não cadastrada", category="danger")
    return redirect(url_for('empresa.empresa_listar'))


@empresa_blueprint.route('/empresa_editar/<empresa_id_crypto>', methods=['GET', 'POST'])
@login_required
@has_view('Empresa')
def empresa_editar(empresa_id_crypto):
    # Decriptografar os ids
    empresa_id = descriptografar(empresa_id_crypto)

    LogsEventos.registrar("evento", empresa_editar.__name__, empresa_id=empresa_id)
    """   Função que altera os valores    """

    if empresa_id > 0:
        # localiza a empresa
        empresa = Empresa.localizar_empresa_by_id(empresa_id)
        # se empresa existir
        if empresa:
            form = EmpresaForm(obj=empresa)  # instânciar o formulário
            new = False  # não é uma empresa nova

            # instância um contrato de assinatura com base no identificador do contrato da empres
            contrato = Contrato.query.filter_by(id=empresa.contrato_id).one_or_none()

            # --------- ATUALIZAR
            if form.contrato.data:  # se os dados já foram preenchidos
                p_d = form.contrato.data
            else:  # pegar os dados selecionados
                p_d = contrato.id
        else:
            flash("Empresa não localizada", category="danger")
            return redirect(url_for('empresa.empresa_listar'))
    else:
        # --------- CADASTRAR
        empresa = Empresa()  # instânciar o objeto empresa
        empresa.id = 0  # informar o id como 0
        form = EmpresaForm()  # instânciar o formulário para empresa
        new = True  # é uma empresa nova
        p_d = form.contrato.data

    # --------- LISTAS
    form.contrato.choices = [(0, '')] + [(contratos.id, contratos.nome)
                                         for contratos in Contrato.query.filter(
            Contrato.ativo == True,
            Contrato.empresa_gestora_id == current_user.empresa_id).all()]
    form.contrato.data = p_d

    # atribuindo o tipo "Cliente" para a empresa
    tipoempresa = Tipoempresa.query.filter_by(nome='Cliente').one_or_none()

    # --------- VALIDAÇÕES E AÇÕES
    if form.validate_on_submit():
        empresa.alterar_atributos(form, current_user.empresa_id, tipoempresa.id, new)
        if salvar(empresa):
            if new:
                empresa = Empresa.query.filter(Empresa.cnpj == form.cnpj.data,
                                               Empresa.empresa_gestora_id == current_user.empresa_id).one_or_none()
                new_admin(empresa, form.enviar_email.data)
            # --------- MENSAGENS
            if empresa_id > 0:
                flash("Empresa atualizada", category="success")
            else:
                flash("Empresa cadastrada, informações enviado ao email", category="success")

            return redirect(url_for("empresa.empresa_listar"))
        else:
            flash("Erro ao salvar a empresa", category="danger")
    else:
        flash_errors(form)
    return render_template("empresa_editar.html", form=form, empresa=empresa)


def new_admin(empresa: [Empresa], enviar_email):
    """    Função para cadastrar os (administradores, grupos) da empresa    """
    senha_nova = ''
    # lista dos administradores
    lista = [{'nome': 'admin', 'descricao': 'administrador',
              'email': empresa.email, 'enviar_email': True, 'senha_temporaria': True},
             {'nome': 'adminluz', 'descricao': 'administrador do sistema',
              'email': config.Config.MAIL_USERNAME, 'enviar_email': False, 'senha_temporaria': False},
             ]

    # laço de repetição
    for valor in lista:
        # cadastro da regra
        perfilacesso = PerfilAcesso(nome=valor['nome'], descricao=valor['descricao'], empresa_id=empresa.id, ativo=True)
        if not salvar(perfilacesso):
            flash("Erro ao salvar o perfil", category="danger")
            break

        # busca a lista de telas liberadas para a empresa
        telascontrato = Telacontrato.query.filter_by(contrato_id=empresa.contrato_id).all()
        for telacontrato in telascontrato:
            # cadastro de perfisacesso para o administrador
            telaperfilacesso = TelaPerfilAcesso(perfilacesso_id=perfilacesso.id, tela_id=telacontrato.tela_id)
            if not salvar(telaperfilacesso):
                flash("Erro ao salvar a tela no perfil", category="danger")
                break

        # instância um novo objeto password_
        senha = Senha()
        if valor['senha_temporaria']:
            # informa a senha de administrador do sistema, a senha não expira
            senha_nova = Senha.senha_aleatoria()
            senha.alterar_senha(senha_nova)
            senha.alterar_expiravel(False)
        else:
            # informa uma senha temporária para o administrador da empresa, e informa a data de expiração da senha
            senha.alterar_senha("aaa-11111")
            senha.alterar_data_expiracao()
            senha.alterar_senha_temporaria(False)
        if not salvar(senha):
            flash("Erro ao salvar a senha do usuário", category="danger")
            break

        # instância um novo objeto usuário
        usuario = Usuario()
        # cria os usuários administradores do sistema para a nova empresa
        usuario.usuario_administrador(nome=valor['nome'] + "_" + empresa.nome_fantasia + "_" + str(empresa.id),
                                      email=valor['email'], empresa_id=empresa.id,
                                      perfilacesso_id=perfilacesso.id, senha_id=senha.id)

        if salvar(usuario):

webapp/templates/sistema/empresa/empresa_cliente.html
{% extends "sistema_base.html" %}
{% block body %}

<body>
<a href="{{ url_for('empresa.empresa_listar') }}">
    <span data-tooltip="VOLTAR">
        <i class="bi-backspace fs-6"></i>
    </span>
</a>


<div id="container">

</div>


</body>


<script type="text/javascript">

      const countries = {
          "Europe": {
            "France": {},
            "Spain": {}
          },
          "America": {
            "North": {
              "USA": {},
              "Canada": {}
            },
            "South": {
              "Brazil": {},
              "Argentina": {}
            }
          }
        };

function createTree(container, data) {
  const ul = container.appendChild(document.createElement('ul'));
  for (const [key, val] of Object.entries(data)) {
    const li = ul.appendChild(document.createElement('li'));
    li.textContent = key;
    if (Object.keys(val).length) {
      createTree(li, val);
    }
  }
}

createTree(document.getElementById('container'), countries);







</script>

{% endblock %}

webapp/templates/sistema/empresa/empresa_editar.html
{% from "macros.html" import exibir_mensagens_erro %}
{% extends "sistema_base.html" %}
{% block body %}
<body>

<a href="{{ url_for('empresa.empresa_listar') }}">
    <span data-tooltip="VOLTAR">
        <i class="bi-backspace fs-6"></i>
    </span>
</a>

<div class="container">
    <div class="row">
        <div class="col-10">
            {% if empresa.id == 0 %}
            <h2>Cadastro de Empresa</h2>
            {% else %}
            <h2>Empresa</h2>
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-10">
            <form action="#" method="POST">
                {{form.csrf_token}}

                {{form.contrato.label}} {{form.contrato}}
                <a href="{{ url_for('contrato.contrato_listar') }}">
                    <span data-tooltip="Atualizar">
                        <i class="bi-caret-down fs-6"></i>
                    </span>
                </a> <br>

                {{form.cnpj.label}} {{form.cnpj(size=20)}}
                <button onclick="pesquisar_cnpj()" type="button"> Validar CNPJ</button>
                <br>
                {{form.razao_social.label}} {{form.razao_social(size=100)}}<br>
                {{form.nome_fantasia.label}} {{form.nome_fantasia(size=100)}}<br>
                {{form.data_abertura.label}} {{form.data_abertura}}<br>
                {{form.situacao.label}} {{form.situacao(size=20)}}<br>
                {{form.porte.label}} {{form.porte(size=20)}}<br>
                {{form.natureza_juridica.label}} {{form.natureza_juridica(size=100)}}<br>
                {{form.cnae_principal.label}} {{form.cnae_principal(size=10)}}<br>
                {{form.cnae_principal_texto.label}} {{form.cnae_principal_texto(size=100)}}<br>
                {{form.inscricao_estadual.label}} {{form.inscricao_estadual(size=30)}}<br>
                {{form.inscricao_municipal.label}} {{form.inscricao_municipal(size=30)}}<br>
                {{form.tipo.label}} {{form.tipo(size=30)}}<br><br>

                {{form.cep.label}} {{form.cep(size=20)}}
                <button onclick="pesquisar_cep()" type="button"> Validar CEP</button>
                <br>
                {{form.logradouro.label}} {{form.logradouro(size=50)}}
                {{form.numero.label}} {{form.numero(size=10)}}<br>
                {{form.complemento.label}} {{form.complemento(size=50)}}
                {{form.bairro.label}} {{form.bairro(size=50)}}<br>
                {{form.municipio.label}} {{form.municipio(size=50)}}
                {{form.uf.label}} {{form.uf(size=10)}}<br>
                {{form.latitude.label}} {{form.latitude(size=80)}}<br>
                {{form.longitude.label}} {{form.longitude(size=80)}}<br>
                {{form.nome_responsavel.label}} {{form.nome_responsavel(size=50)}}<br>
                {{form.email.label}} {{form.email(size=50)}}<br>
                {{form.telefone.label}} {{form.telefone(size=20)}}<br>
                {{form.ativo.label}} {{form.ativo(size=20)}}<br>
                {{form.enviar_email.label}} {{form.enviar_email(size=20)}}<br>


                {% if empresa.id == 0 %}
                <input onclick="empresa_editar({{ empresa.id }}, 'action')" type="submit" value="Cadastrar"/>
                {% else %}
                <input onclick="empresa_editar({{ empresa.id }}, 'action')" type="submit" value="Atualizar"/>
                {% endif %}
            </form>

            <br>

            {% if empresa.id == 0 %}
            <form action="{{ url_for('empresa.cadastrar_lote_empresas') }}" enctype="multipart/form-data" method="POST">
                {{ form.file.label }} {{ form.file }}
                <input type="submit" value="Cadastrar_lote"/>
            </form>
            <a href="{{ url_for('empresa.gerar_padrao_empresas') }}">Gerar Arquivo Base</a>
            {% endif %}

        </div>
    </div>


</div>


</body>

<script src="/static/js/consulta_cep.js" type="text/javascript"></script>
<script src="/static/js/consulta_cnpj.js" type="text/javascript"></script>


{% endblock %}

webapp/templates/sistema/empresa/empresa_listar.html
{% extends "sistema_base.html" %}
{% block body %}
<body>
<a href="{{ url_for('sistema.index') }}">
    <span data-tooltip="VOLTAR">
        <i class="bi-backspace fs-6"></i>
    </span>
</a>


<div class="container">
    <div class="row">
        <div class="col-10">
            <h2> EMPRESAS </h2>
        </div>

        <div class="col-4">
            <input class="form-control" id="myInput" placeholder="Filtrar.." type="text"><br>
        </div>

        <div class="col-1">
            <a href="{{ url_for('empresa.empresa_editar', empresa_id_crypto=0) }}">
               <span data-bs-target="#modal" data-bs-toggle="modal" data-tooltip="INCLUIR EMPRESA">
                   <i class="bi-house-door fs-4">+</i>
               </span>
            </a>
        </div>

        <div class="col-1">
            <a href="{{ url_for('empresa.gerar_csv_empresas') }}">
                <span data-tooltip="GERAR CSV">
                    <i class="bi-download fs-4"></i>
                </span>
            </a>
        </div>

    </div>

    <div class="row">
        <div class="col-10">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">CNPJ</th>
                    <th scope="col">NOME FANTASIA</th>
                    <th scope="col">CONTRATO</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
                </thead>

                <tbody id="myTable">
                {% for empresa in empresas %}
                <tr>
                    <th scope="row">{{ empresa.cnpj }}</th>
                    <td>{{ empresa.nome_fantasia }}</td>
                    <td>{{ empresa.contrato.nome }}</td>
                    <td>
                        <a href="{{ url_for('empresa.empresa_excluir', empresa_id_crypto=empresa.id_criptografado) }}"
                           onclick="return deleteItem();">
                            <span data-tooltip="Excluir">
                               <i class="bi-trash fs-6"></i>
                            </span>
                        </a>
                    </td>
                    {% if empresa.ativo == True %}
                    <td>
                        <a href="{{ url_for('empresa.empresa_ativar', empresa_id_crypto=empresa.id_criptografado) }}">
                        <span data-tooltip="Desativar">
                            <i class="bi-hand-thumbs-up fs-6"></i>
                        </span>
                        </a>
                    </td>
                    <td>
                        <a href="{{ url_for('empresa.empresa_acessar', empresa_id_crypto=empresa.id_criptografado) }}">
                        <span data-tooltip="Acesso">
                            <i class="bi-box-arrow-in-down fs-6"></i>
                        </span>
                        </a>
                    </td>

                    {% else %}
                    <td>
                        <a href="{{ url_for('empresa.empresa_ativar', empresa_id_crypto=empresa.id_criptografado) }}">
                        <span data-tooltip="Ativar">
                            <i class="bi-hand-thumbs-down fs-6"></i>
                        </span>
                        </a>
                    </td>
                    <td></td>
                    {% endif %}
                    <td>
                        <a href="{{ url_for('empresa.empresa_editar', empresa_id_crypto=empresa.id_criptografado) }}">
                        <span data-tooltip="Informações">
                            <i class="bi-caret-right fs-6"></i>
                        </span>
                        </a>
                    </td>


                </tr>
                {% endfor %}
                </tbody>
            </table>


        </div>
    </div>
</div>

</body>


{% endblock %}

webapp/templates/sistema/empresa/empresa_registrar.html
{% extends "base.html" %}
{% block body %}
<body>
<a href="{{ url_for('empresa.empresa_listar') }}">Voltar</a>
<form action="{{ url_for('empresa.empresa_registrar', token=token) }}" method="POST">
    {{form.csrf_token}}

    <h2>Cadastre sua Empresa</h2>

    {{form.nome_fantasia.label}} {{form.nome_fantasia(size=20)}}<br>
    {{form.razao_social.label}} {{form.razao_social(size=80)}}<br>
    {{form.cnpj.label}} {{form.cnpj(size=20)}}<br>
    {{form.cep.label}} {{form.cep(size=20)}}<br>
    {{form.numero.label}} {{form.numero(size=20)}}
    {{form.complemento.label}} {{form.complemento(size=20)}}
    {{form.logradouro.label}} {{form.logradouro(size=20)}}<br>
    {{form.bairro.label}} {{form.bairro(size=20)}}
    {{form.municipio.label}} {{form.municipio(size=20)}}
    {{form.uf.label}} {{form.uf(size=20)}}<br>

    {{form.email.label}} {{form.email(size=20)}}<br>
    {{form.telefone.label}} {{form.telefone(size=20)}}<br>
    {{form.contrato.label}} {{form.contrato}}<br>

    <input type="submit" value="Cadastrar"/>
</form>

</body>

<script src="/static/js/consulta_cep.js" type="text/javascript"></script>

{% endblock %}

webapp/templates/sistema/empresa/interessado_listar.html
{% extends "sistema_base.html" %}
{% block body %}
<body>

<a href="{{ url_for('sistema.index') }}">
    <span data-tooltip="VOLTAR">
        <i class="bi-backspace fs-6"></i>
    </span>
</a>
<br>

<div class="container">
    <div class="row">
        <div class="col-9">
            <h2> INTERESSADOS </h2>
        </div>


        <div class="col-4">
            <input class="form-control" id="myInput" placeholder="Filtrar.." type="text"><br>
        </div>
        <div class="col-1">
            <button onclick="exportar_lista('interessados.csv', 1)" type="button">
                <span data-tooltip="EXPORTAR LISTA">
                    <i class="bi-download fs-6"></i>
                </span>
            </button>
        </div>
    </div>

    <div class="row">
        <div class="col-10">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">CNPJ</th>
                    <th scope="col">NOME_FANTASIA</th>
                    <th scope="col">EMAIL</th>
                    <th scope="col">TELEFONE</th>
                    <th scope="col">DATA SOLICITAÇÃO</th>
                    <th scope="col">DATA CADASTRO</th>
                    <th scope="col"></th>
                </tr>
                </thead>

                <tbody id="myTable">
                {% for interessado in interessados %}
                <tr>
                    <th scope="row">{{ interessado.cnpj }}</th>
                    <td>{{ interessado.nome_fantasia }}</td>
                    <td>{{ interessado.email }}</td>
                    <td>{{ interessado.telefone }}</td>
                    <td>{{ interessado.data_solicitacao }}</td>
                    <td>{{ interessado.data_cadastro }}</td>

                    {% if interessado.data_cadastro == None %}
                    <td>
                        <a href="{{ url_for('empresa.enviar_link', interessado_id=interessado.id) }}">
                                <span data-tooltip="Enviar Link">
                                    <i class="bi-caret-right fs-6"></i>
                                </span>
                        </a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>


</div>


</body>
<script src="/static/js/exportar_consulta.js" type="text/javascript"></script>
<script src="/static/js/filtro_coluna.js" type="text/javascript"></script>


{% endblock %}